CREATE TABLE IF NOT EXISTS ACCOUNT
(
    accountType NVARCHAR(20)  NOT NULL,
    id NVARCHAR(40)  NOT NULL,
    clientID NVARCHAR(40)  NOT NULL,
    balance DOUBLE,
    isWithdrawalAllowed BOOLEAN,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS TRANSACTION
(   transactionID LONG NOT NULL,
    operation NVARCHAR(40) NOT NULL,
    accountType NVARCHAR(20)  NOT NULL,
    id NVARCHAR(40)  NOT NULL,
    clientID NVARCHAR(40)  NOT NULL,
    amount DOUBLE,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES ACCOUNT(id)
);

create table ROLEENTITY
(
    id INTEGER NOT NULL,
    name NVARCHAR(20) NOT NULL,
    PRIMARY KEY (id)
);

create table USERENTITY
(
    id INTEGER NOT NULL,
    login    NVARCHAR(50) NOT NULL,
    password NVARCHAR(500) NOT NULL,
    ROLEENTITY_ID  INTEGER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (ROLEENTITY_ID) REFERENCES ROLEENTITY(id)
);
INSERT INTO ROLEENTITY VALUES ( 1, 'ROLE_ADMIN' );
INSERT INTO ROLEENTITY VALUES ( 2, 'ROLE_USER' );

